[package]
name = "bevy_particle_life"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", features = ["bevy_dev_tools"] }
bevy_egui = "0.29.0"
bevy_vello = "0.6.1"
rand = "0.8.5"
rayon = "1.10.0"
